### ISSUE TITLE
[Bug] Coverage Fails on waitForNSeconds

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#103]
Observe that this function

https://github.com/gnosis/dex-contracts/blob/300b69cf8b5006bd763da09c1bbe602a7100f43a/test/utilities.js#L118-L122

when changed to 

```js
const waitForNSeconds = async function(seconds, web3Provider=web3) {
  const currentBlock = await web3Provider.eth.getBlockNumber()
  const currentTime = (await web3Provider.eth.getBlock(currentBlock)).timestamp
  console.log("Current Time: ", currentTime)
  await send("evm_mine", [currentTime + seconds], web3Provider)
  const nextBlock = await web3Provider.eth.getBlockNumber()
  console.log("New Time: ", (await web3Provider.eth.getBlock(nextBlock)).timestamp)
}
```

outputs 
```
Current Time:  1559735013
New Time:  1559735013
```
when running `./node_modules/.bin/solidity-coverage`

but actually works when running `truffle test`

Subscribing @fleupold or @josojo. Any ideas?

**Comment by fleupold** [comment]
Nice catch! Looks like `evm_mine` is not working as expected in their "coverage-enabled fork of the ganache-cli client".
Could you ask on their [github](https://github.com/sc-forks/solidity-coverage) by creating an issue with a minimal example?

**Comment by fleupold** [comment]
We could first also try if ` await send('evm_increaseTime', [seconds])` works
