### ISSUE TITLE
Emit Event on Contract Deployment

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#11]
This event is required but the Event listener to all account balances to 0 for each `accountId` and `tokenId`. 

This should emit the 
```js
event SnappInitialization(bytes32 stateHash, uint8 maxTokens, uint16 maxAccounts);
```

It might also make sense to include these values as part of the constructor's parameters. 

```js
constructor (bytes32 _stateInit, uint8 _maxTokens, uint16 _maxAccounts) public {
    // The initial state should be Pederson hash of an empty balance array
    stateRoots.push(_stateInit);
    MAX_ACCOUNT_ID = _maxAccounts;
    MAX_TOKENS = _maxTokens;
    emit SnappInitialization(_stateInit, _maxTokens, _maxAccounts);
}
```

but then we couldn't declare `MAX_ACCOUNT_ID` and `MAX_TOKENS` as constants... Is this a problem @josojo.

**Comment by josojo** [comment]
I think it is better to just have the constants written into the smart contracts directly, and do it while the smart contracts will be deployed. 

these constants need to be hard coded exactly like the snark logic. If you make only the maxToken counts updateable but not the snark logic, you have not gained anything

**Comment by bh2smith** [comment]
So then, just the event is enough
```js
constructor (bytes32 _stateInit) public {
    // The initial state should be Pederson hash of an empty balance array
    stateRoots.push(_stateInit);
    emit SnappInitialization(_stateInit, _maxTokens, _maxAccounts);
}
```

In this case, we should also hard code the stateInitHash directly into the first state.
