### ISSUE TITLE
[Bug] maxUnreservedOrderCount returns 756

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#113]
This function:

https://github.com/gnosis/dex-contracts/blob/e23b6d71f8eeaa888095dfa880857e7fde952030/contracts/SnappAuction.sol#L234-L236

is expected to return 500 (i.e. `AUCTION_BATCH_SIZE - (AUCTION_RESERVED_ACCOUNTS * AUCTION_RESERVED_ACCOUNT_BATCH_SIZE)` but it returns 756.

This is because both `AUCTION_RESERVED_ACCOUNTS` and `AUCTION_RESERVED_ACCOUNT_BATCH_SIZE` are of type `uint8` so the product `AUCTION_RESERVED_ACCOUNTS * AUCTION_RESERVED_ACCOUNT_BATCH_SIZE` overloads an evaluates to 244.

There should be a unit test showing that this value is the expected result.

Furthermore, it would appear that the unit tests for `placeStandingSellOrder` are not making use of the contract constants. For example, 

https://github.com/gnosis/dex-contracts/blob/e23b6d71f8eeaa888095dfa880857e7fde952030/test/snapp_auction.js#L185-L189

This is dangerous!

**Comment by josojo** [comment]
good catch. I will take care of it.

**Comment by fleupold** [comment]
Yes, great 🎣 and agree that there should have been a unit test for it. Sorry I didn't add it. Should be very quick to fix (making `placeStandingSellOrder` use the constants is not as critical and can be a separate PR).
