### ISSUE TITLE
encode vs encodePacked

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#117]
Currently all rolling hashes are/have been computed using `encodePacked` -- as per recommendation of the solidity compiler. It was recently brought up by @joso that we might want to consider using `abi.encode` instead to avoid some possibly issues with leading zeros in the `shaHash`. Thought it would be a good idea to discuss these concerns in a separate thread (i.e. here).

As a reference to the concern, Below is the quote from a different location

> @josojo; I was wondering, whether there is a risk in case we are getting leading zeros in the sha hash and in the id. In this case the backend infrastructure would not be aware of where to truncate. I think it could cause problems and we might want to switch to encode only.
However, it might all work fine, as every string starts with 0x anyways and then there will not be any truncating. But then we can use encode anyways, instead of encodePacked

**Comment by fleupold** [comment]
I looked at https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html#non-standard-packed-mode and don't understand the concern. We are only using fixed sized fields (bytes32 to be specific). How would there be an ambiguous packing?

Can you give an example of potential values that might cause a problem?

**Comment by josojo** [comment]
Alright, double checked it. No issue. 
Sorry, my thought was misleading
