### ISSUE TITLE
[Snapp] Submit orders on other's behalf

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#130]
Rather than depending on `msg.sender` to place an order, dedicated order collectors can submit on registered member's behalf.

This involves using `ECRecover` from signature contained in first 65 bytes of a `packedOrder`.

https://github.com/gnosis/dex-contracts/blob/d6d645d499cf6b9206e7a28e136b5fb9476013da/contracts/SnappAuction.sol#L169

**Comment by josojo** [comment]
Martin and I just discovered that others are also hashing the contract address into the orderhash as well. This is a good replay-protection between all the signatures that people might sign on different exchanges and on different chains.

See here as an example:
https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819#code
