### ISSUE TITLE
[Bug] Failing Unit Test

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#137]
Not sure how this snuck in.

```
calculateOrderHash()
      ✓ calculates the orderHash with standingOrderIndex = [0,...,0] (575ms)
      1) throws is standingOrderIndex is not valid in slot

    Events emitted during test:
    ---------------------------

    OwnershipTransferred(previousOwner: <indexed>, newOwner: <indexed>)
    SnappInitialization(stateHash: 0x0000000000000000000000000000000000000000000000000000000000000000, maxTokens: 30, maxAccounts: 100)
    AuctionInitialization(maxOrders: 1000, numReservedAccounts: 50, ordersPerReservedAccount: 10)
    MinterAdded(account: <indexed>)
    MinterAdded(account: <indexed>)
    Transfer(from: <indexed>, to: <indexed>, value: 300000000000000000000)
    Approval(owner: <indexed>, spender: <indexed>, value: 300000000000000000000)
    Transfer(from: <indexed>, to: <indexed>, value: 300000000000000000000)
    Approval(owner: <indexed>, spender: <indexed>, value: 300000000000000000000)
    StandingSellOrderBatch(currentBatchIndex: 0, validFromAuctionId: 0, accountId: 0, packedOrders: 0x00000000000000000000000300000000000000000000000300000000000000000000000000010000000000000000000000010100)
    StandingSellOrderBatch(currentBatchIndex: 1, validFromAuctionId: 1, accountId: 0, packedOrders: 0x00000000000000000000000300000000000000000000000300000000000000000000000000010000000000000000000000000100)
```

**Comment by fleupold** [comment]
Is it possible that this is local to you? It looks like travis is green on master: https://travis-ci.org/gnosis/dex-contracts/builds/548563944

**Comment by bh2smith** [comment]
Yes, actually it may have been a result of the `audit fix`

**Comment by bh2smith** [comment]
Unfortunately @fleupold , I don't think that is the case. I have removed `node_modules`, reinstalled and ran the coverage report. Would you try checking out master and executing `npm run coverage`. I will rerun the test on the current master.

**Comment by fleupold** [comment]
I can reproduce that `npm test` fails. However, I reran travis and it's still green: https://travis-ci.org/gnosis/dex-contracts/builds/548563944

Interestingly running `npm test` gives me:

`AssertionError: Did not fail`

whereas running `npm coverage` gives an assertion, just not the expected one:

`AssertionError: Expected to fail with non-valid standingOrderBatch referenced, but failed with: Error: Returned error: VM Exception while processing transaction: revert`

@josojo as the author of the test case, do you have any idea what could be the reason?

**Comment by fleupold** [comment]
I assume this could be due to the fact that a revert in a view function is not propagated up to the js instances the same way as non-view functions.

**Comment by fleupold** [comment]
Found the issue: #138
