### ISSUE TITLE
Multi-Phase Auction part I (Solution Bidding)

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#150]
This is the time period between order collection (i.e. batch closing) referred to as **Solution Bidding**. During this phase, _solvers_ will send a transaction containing the `auctionId`, their claimed achievable `objectiveValue` (uint128) and a `stateRoot` commitment that they claim to have a solution for.

The contract will only keep those proposals which exceed the _current maximum_ as already stored on the contract (indexed by `auctionId`). This phase will take `3` minutes (as is the current batch time for order collection). After this phase has completed, the `msg.sender` with the current largest commitment will be expected to provide their full solution (in Phase II)

Please refer to our discussion on [Auction Resolution Timing](https://github.com/gnosis/dex-research/issues/27) for justification and further details on how this implementation came to be.

**Comment by fleupold** [comment]
> their claimed achievable objectiveValue (uint128)

Currently, this is a u256 (cf. [here](https://github.com/gnosis/dex-services/blob/2115b07ebdd88e5e430675f9aade9e14687c9973/driver/src/price_finding/price_finder_interface.rs#L9)). Is there a reason this should become u128?

**Comment by bh2smith** [comment]
> Is there a reason this should become u128?

I assumed that we would be using the same type as the amounts in all other parts of the contract code. I have no strong feelings about this although I could imagine that using u128 for both amounts and surplus could  result in _overflow_ (e.g.`2^128-1 + 2^128 -1`). However, I am not sure that using u256 just for the potential overflow is normally how such an issue is handled. Do we have any reason for assuming that the surplus would require u256?

**Comment by fleupold** [comment]
I'm not sure why we chose amounts to be 128 bits. In the long run, amounts that are posted on chain (buy/sell amount, volumes) will be 32bit compressed numbers so the parity between surplus and volumes will likely have to go away anyways. 

Generally, I think state balances should be 256 bits (since this is also the native word width for hashing). If balances are 256 bits, I believe it would make sense if the uncompressed amounts to be traded were the same width and thus also the surplus.

**Comment by bh2smith** [comment]
In pseudo-generic terms, this is expected to look as follows;

```js
function auctionSolutionBid(
    uint auctionId,
    uint proposedObjectiveValue,
    bytes32 proposedStateRoot,
    bytes32 _currOrderHash,
    bytes32 _currStateRoot
) public onlyOwner() {
    // Verify state root and order hash before continuing.
    require(coreData.stateRoots[stateIndex()] == _currStateRoot, "Incorrect state root");
    require(auctions[auctionId].shaHash == _currOrderHash, "Order hash doesn't agree");

    // Ensure that auction batch is inactive, unprocessed and in correct phase for bidding.
    require("Auction has not already been applied");
    require("Requested order slot exists");
    require("Requested order slot is inactive");
    require("Bidding period for this auction has not expired");

    // Ensure proposed value exceeds current max.
    require(
        proposedObjectiveValue > auctionResults[auctionId].objectiveValue,
        "Proposed objective value is less than existing"
    );
    // TODO - Collect bond from new winner, return bond from previous winner.
    // require(transfer(msg.sender, address(this), BOND_AMOUNT));
    // if (auctionResults[auctionId].sender(this) != 0x0) { // This if is VERY IMPORTANT. Don't want to burn bonds
       // require(transfer(address(this), auctionResults[auctionId].solver, BOND_AMOUNT));
    // }
    auctionResults[auctionId] = AuctionResult({
        solver: msg.sender,
        objectiveValue: proposedObjectiveValue,
        tentativeState: proposedStateRoot
    });
}
```

**Comment by fleupold** [comment]
Pseudocode looks good to me. We also have to make sure `auctionId - 1` has already been applied, so that we don't create weird gaps.

**Comment by bh2smith** [comment]
> We also have to make sure auctionId - 1 has already been applied...

Yes, thanks for mentioning, I will also include this;

```js
require(
    slot == 0 || auctions[slot-1].appliedAccountStateIndex != 0, 
    "Previous auction not yet resolved!"
);
```

Also note that I will leave the order hash verification out for the time being because its a little more inconvenient that so cleanly described above... In fact, under the current implementation (which contains standing orders), this constraint is more like the following:
```js
require(
    calculateOrderHash(slot, _standingOrderIndex) == _orderHash,
    "Order hash doesn't agree"
);
```
and also requires passing the `_standingOrderIndex`.

@josojo and/or @fleupold, is now the time to start transferring bonds around, or should I leave this part commented out for a later feature?

**Comment by fleupold** [comment]
>  is now the time to start transferring bonds around

I think the completion of this task should include bonding.
