### ISSUE TITLE
Multi-Phase Auction part II (Auction Settlement/Solution Revealing)

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#151]
As a simplified version of the general discussion on [Auction Phase Timing](https://github.com/gnosis/dex-research/issues/27), this phase will allocate a fixed/finite time interval of `3 minutes` to the **Auction Settlement** phase occurring immediately after Solution Bidding (described in #150) as follows:

1. The first half of the time is specially reserved for the address currently stored on the contract from Phase I (i.e. the winner of the bidding).

2. The second half of the time is a free-for-all for which the contract accepts new state proposals (with solution) from anyone. This state proposal is considered temporary and updatable by anyone proposing a transition with higher volume during this period.

**Note that**

1. If the solution is provided by the phase I winner during the reserved time, then the auction is considered settled while the second half of the time interval does not consider the auction settled until the time has completed.

2. There is a potential security gap in the above description; In the second half of this phase, we say that "anyone" can submit a state update. Since there is currently no implementation of challenge-response or fraud-proof mechanism. This "anyone" would be able to drive the contract into an invalid state. Because of this, we will temporarily disable the decentralized aspect here and say, for the purpose of testing, that `onlyOwner` will be able to do so.

**Comment by bh2smith** [comment]
Some pseudo-generic code regarding the first half of the auction might look like this;

```js
function winnerApplyAuction(
    uint slot,
    bytes memory pricesAndVolumes
    // bytes32 _currStateRoot,                // Already verified during bidding.
    // bytes32 _orderHash,                    // Already verified during bidding.
    // uint128[] memory _standingOrderIndex,  // TODO - remove this
)
    public onlyOwner()
{
    require("Auction not already applied");
    require(
        block.timestamp > auctions[slot].creationTimestamp + 6 minutes,
        "Requested auction still in bidding phase."
    );
    require(
        block.timestamp < auctions[slot].creationTimestamp + 450 seconds,  // 6 + 3/2 minutes
        "Too late for winning result to submit solution"
    );
    require(
        auctionResults[slot].solver == msg.sender,
        "Only winner of bidding phase may apply auction here"
    );
    applyAuction(slot, auctionResults[slot].tentativeState, pricesAndVolumes);
}

function applyAuction(
    uint slot,
    bytes32 newStateRoot,
    bytes memory pricesAndVolumes
)
    internal  // NOTE INTERNAL!
{
    coreData.stateRoots.push(newStateRoot);
    auctions[slot].appliedAccountStateIndex = stateIndex();
    auctions[slot].shaHash = sha256(pricesAndVolumes);
    emit AuctionSettlement(slot, stateIndex(), newStateRoot, pricesAndVolumes);
}
```

Next step here is to deal with the second half (i.e. when the solution is not provided by the winner within the first half of settlement phase).

**Comment by bh2smith** [comment]
Also! We will need to consider here, the possibility that no solution is proposed and no solution is provided during any of the multi-phases. It would be natural to apply the trivial auction (i.e. where no trade execution occurs and the `accountState` remains the same). This would essentially be the case if both the bidding and revelation phase are expired, and auctionResults.solver is the zero address.

**Comment by bh2smith** [comment]
We will refer to the second sub-phase here as `fallbackApplyAuction`. This should be a final round of bidding that updates the tentative solution in the new struct `auctionResults[auctionId]` if the auction was not already applied in the `winnerApplyAuction` sub-phase described above. The problem here is that this phase is only capable of updating the tentative state root (while this phase is considered active) and may require a second transaction to actually move this tentative state into a semi-finalized state.

One option here is to expand on the `bytes32[]  stateRoots` (array) of account states including a field for its describing whether it is proposed, semi-finalized or final. 

Alternatively, it may also suffice to store this type of auction finalization information directly on the struct uniquely containing auction batches. In the latter scenario, it would be necessary to first address Issue #153 (which moves the auctions mapping away from the generic `PendingFlux` structure used for both deposits and withdrawals into its own `PendingAuction` struct that can be expanded for its own unique purposes.)

In the end, it may also suffice to have an additional function called `nudgeAuction` which (after Solution Revelation period has expired) simply moves a tentative state into the actual one!

**Comment by fleupold** [comment]
@bh2smith can't we just allow anyone to apply the hardcoded fallbackSolution if

- either the bidding period ended without a single bid
- or the revelation period expired without a single revelation

❓

**Comment by bh2smith** [comment]
Yes @fleupold, that is what I thought I was describing here. 

Perhaps not exactly like that, but we had discussed a scenario where half the solution period is allocated to the winner and the other half is opened up for others to supply a solution. My impression was that the second half wouldn't be considered "accepted" until the entire period is over. This means that the state root is only updated in one of the 2/3ish possible ways:

1. When winner submits a solution during the first half of allotted revelation time.
2. When revelation period is over, anyone can call `nudgeAuction(slot)`:
    - If: there is a proposed root with solution use that
    - else: apply trivial solution

I hope this clears things up. Please let me know if you would prefer to do things differently. We have @josojo  in the office today, perhaps I can show him these ideas on the whiteboard.
