### ISSUE TITLE
[stablecoin converter] Compromises to make all data available on-chain without events

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#158]
In the previous meetings, we raised that it would be beneficial to have all relevant data stored in the contract, so that we don't have to maintain any backend-logic for the exchange.

In this issue, I want to challenge this paradigm, and highlight its drawbacks:

If we want to make orders available on-chain, I guess we have to pick one of the following two strategies, both have their caveats.
**conecpt 0:**
// User -> order
mapping (address => bytes32[])
where the 32 bytes are used to represent the order. This requires some encoding of orders to bytes32.

This makes canceling and referencing hard. If people want to refer to a specific order they would provide the (address, id in array), but then any deletion in the array would shift all indexes. We could also argue that people can never delete their orders (only cancel them), but this might be a big waste of resources.

**conecpt 1:**
// User -> orderIndex -> order
mapping (address => mapping( uint => bytes32)
where the 32 bytes are used to represent the order.

Now, the deletion issue is solved, as no re-indexing is used. But now, the issue is that we need to maintain somehow another counter, which stores the max index, in order to insert new elements. Also, in order to get all orders, we would have to write potentially big `for loops` in solidity, which is not the best design pattern (though these for loops would only be used in view functions)

**conecpt 2:**
// hash(orderData) -> openVolume
mapping (bytes32 => uint)
This solution would not have any of the previously mentioned issues, but for sure needs more backend-infrastructure.

**Front-end team feedback**
The front-end team also state that they would prefer to get their data from a postgres databank instead of reading it directly from the blockchain.

**Solver**
For the solver a minimal backend-infrastructure is needed anyway

**Overall comment**
Having a minimal backend storing only the current orders would be beneficial in many small places and would not require much more effort, as it is needed for backend anyways.

**Comment by fleupold** [comment]
I think concept 0 should work. Regarding your concerns:

> where the 32 bytes are used to represent the order.

It could also be a list of a more elaborate struct (no need to constraint on bytes 32).

> This makes canceling and referencing hard.

Cancelling would set the validUntil index to the current batch index. No need for reordering. To free storage we could consider overriding stale data with 0s (without reducing the index).

 > The front-end team also state that they would prefer to get their data from a postgres databank 

Having data only for UI purposes has different reliability requirements as far as consistency, and availability is concerned. 
Also, a minimal UI could arguably function without historic deposit/settlement information (which at this point seems to be the only data that is not available on chain).

> For the solver a minimal backend-infrastructure is needed anyway

Even for the  component that is already necessary, I'd argue it makes a difference if a it reads from one data source (the smart contract) or two different data sources which could have a data race (not speaking of the work to build the other component).

Generally my feeling is that you underestimate the amount of work it will be to create this component. It also adds dependencies in the form of "A cannot be built before B is ready".
Looking at the amount of effort it was to launch the MGNPool (contract + driver script only) vs. the progress we have made so far on the SnappAuction I believe there is a lot of infrastructural overhead (on top of just being more complex) in the latter system.

In the spirit of getting this MVP out quickly I'd therefore strongly prefer an on-chain only system and not start the feature creep by adding another component lightheartedly.

**Comment by anxolin** [comment]
Thank Alex for the proposals.

What about:
```
// user-> orderIds
mapping (address => uint[]) public userOrderIds;

// Orders
Order[] public orders;
struct Order {
        // ...
}
```

This way, it's simple to get info of an order just knowing it's id. It would be a bit more expensive but it should be fine for sake of simplicity.

Consuming the info from blockchain in a simple way, I think is good for sake of letting others understand better the contract. It allows simpler integrations. Cache layers can be added always on top.

Regarding if the FE should be using directly the smart contracts or another datasource it depends on how simple the app is going to be. I feel we should try to first define some basic "Use case diagrams" to understand the scope, then we try to iterate in some basic wireframes so we are clear on what it should look like. This also would guide our smart contract designs, and components architecture.

I'll vote for only SC if it's super basic app.
I'll vote for having a cached layer if we start to have some non-trivial functionalities.

Additionally, I have one a technical question regarding loops, maybe one of you have some thoughts. I haven't seen this too much in smart contract, but for arrays that grow a lot (like orders in this case), wouldn't it make sense to have a view function where you input the "start index" and the "page size" and they return just one single page of results?

**Comment by josojo** [comment]
Closing, as it was implemented in the referenced PR
