### ISSUE TITLE
[spelling] exectuedAmount ...

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#222]
exectuedAmount is spelled incorrectly

**Comment by anxolin** [comment]
I struggle a little with the names of all the last issues. 
Some titles feel a bit like descriptions, other incomplete or rushed.
It's not very easy to follow.

**Comment by josojo** [comment]
:) They are basically notes taken during a meeting. I will improve it on Friday.

**Comment by bh2smith** [comment]
What is this issue?
