### ISSUE TITLE
Objective value cannot be <= 0

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#242]
For some objective values (e.g. utility - disregarded utility) it should be possible to have a value of zero or less (0 could mean everyone is trading at the indifference price, which should be allowed).

Thus this line

https://github.com/gnosis/dex-contracts/blob/1883cb8b42ef46da22a359cb12c573c50fe9f0d9/contracts/StablecoinConverter.sol#L333

should only be evaluated if there is already another solution present. At the beginning of each auction the currentObjectiveValue will be set to 0 without any solution.

**Comment by josojo** [comment]
@bh2smith coded the utility function so nicely, that even for an indifferent price, we will get a positive utility.

He describes it best in this PR
https://github.com/gnosis/dex-contracts/pull/236

**Comment by bh2smith** [comment]
> He describes it best in this PR #236

Unfortunately, most of the discussion appears to have been buried underneath several commits and it no longer easily accessible. However, I have included pieces of this discussion in the following thread https://github.com/gnosis/dex-contracts/pull/229#discussion_r339912373

In summary, I would argue that this is not a bug and is working as intended. However, I can agree that our objective metric for solution ranking is sub-par.  There are unit tests in place (or under construction) that will demonstrate the corresponding examples. 

Finally, observe a key fact: Any solution with negative objective will be beaten by the trivial solution (immediately) at no expense by any competing solvers. Thus,

1. There is no reason to allow for negative solutions
2. There is no reason to allow anyone to submit a trivial solution.

**Comment by fleupold** [comment]
Ok, thanks for the explanation.
