### ISSUE TITLE
[Typo?] Claimed return values with no explicit return

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#258]
The following two functions claim to return `uint`, but don't explicitly return anything. Was this intended? 

https://github.com/gnosis/dex-contracts/blob/6c4bb7dc30eb0213997dfcfbe5cdcbb0daa3b4cf/contracts/StablecoinConverter.sol#L267-L281

**Comment by fleupold** [comment]
Likely unintended, but flagging @josojo

**Comment by josojo** [comment]
Yeah, definitively unintended. Weird that the compiler is not checking it

**Comment by bh2smith** [comment]
Great, then the fix has already been made in #259. Just waiting on approval!
