### ISSUE TITLE
[Bug] All stableX scripts rely on ganache for account addresses

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#269]
the fact that we fetch account addresses using `accounts[argv.accountId]` in all the stableX scripts renders all of their potential use as a CLI useless.

Every instance of `accounts[argv.accountId]` should be replaces with a contract query analogous to how token addresses are recovered from their ID `const token_address = await instance.tokenIdToAddressMap.call(argv.tokenId)`

https://github.com/gnosis/dex-contracts/blob/0f1995cc25ebd94daacdd5247bd843f194cf93ac/scripts/stablex/claim_withdraw.js#L20

**Comment by bh2smith** [comment]
@josojo and @fleupold - I just noticed that this is not going to be so easy, because users are not stored on the contract in the same way that tokens are listed...
```
    // Iterable set of all users, required to collect auction information
    IterableAppendOnlySet.Data private allUsers;
    using IterableAppendOnlySet for IterableAppendOnlySet.Data;
```

If we want to recover from this, we would need to store users as follows:

```
IdToAddressBiMap.Data private registeredTokens;
```

**Comment by fleupold** [comment]
Can you not iterate over the allUsers set and find the address or index you are interested in? Given it's a view function O(1) lookup shouldn't be a requirement.

**Comment by bh2smith** [comment]
> Can you not iterate over the allUsers set and find the address or index you are interested in? Given it's a view function O(1) lookup shouldn't be a requirement.

Should I assume that this append only set has a root?

**Comment by fleupold** [comment]
@bh2smith can you elaborate on what the issue with the current approach is? As far as I know, we don't use the `accountId` inside the smart contract anywhere, so it's basically just the id that you are using given your seed phrase or private key (e.g. `accountId=0` is the first address that can be generated from your see). So you could use `accountId=0` if you want to interact with rinkeby/mainnet deployments.

I'm somewhat sure we have already tried this in the past.

**Comment by bh2smith** [comment]
> can you elaborate on what the issue with the current approach is

The problem with this is that none of these scripts can be used in a user facing CLI, nor can they be used by the front end (which was, I thought, an original intention). A user in the terminal, or the front end will not be able to run with `accountId` as a script parameter (because they don't have one). `claim_withdraw --accountId 1`. This makes these scripts essentially useless to everyone but the e2e tests in the `dex-services` repo. The script should be changed to accept `userAddress` so that people can actually use it.

**Comment by fleupold** [comment]
I think that even if you are using the script in a CLI environment, you will have a web3 provider with unlocked accounts (e.g. the one truffle injects from the mnemonic when we deploy on rinkeby).

Thus the web3 provider will have a `getAccounts()` method which returns a list in which you can index with `accountId`. So `accountId=1` would mean the second account that can be generated from the provided mnemonic.

I'm not sure how having the address directly as an argument would help. How would signing the txs work if we don't have an unlocked web3 provider?

I also don't think the frontend intended on using the scripts. They are too tightly coupled to CLI arguments and don't provide much logic other than translating the arguments into a contract invocation. The frontends will call the contracts directly.
