### ISSUE TITLE
[bug] Buy OWL for free

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#291]
Assume someone puts a order into our system, which reads like this:

buyToken = feeToken
sellToken = fakeToken
minBuyAmount = 50
sellAmount = 50

Now, a solution submitter could create a solution only containing this single order with the prices:

Price(fakeToken) = 10^30
Price(feeToken) = 10^18

Now, due to rounding, we would get that 0 fakeTokens would be sold for 50*10**12 feeTokens.

Then the token conservation check passes, although it should not.

Proposed solution:
(1) Do not accept solutions, where one calculated sellAmount == 0

Edit: Initially I had an error in the prices! But Tom corrected it. Thanks

**Comment by nlordell** [comment]
~~Would just (2) be sufficient?~~
Looks like there's only (1) now :)

**Comment by bh2smith** [comment]
Technically speaking, although I will surely regret this, there is no reason why the contract should even allow orders to buy the fee token. This would change all of our test examples, but I believe this would be an easy solution to both this and #292.
