### ISSUE TITLE
Upgrade To Stable NodeJS

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-contracts#329]
We currently require an old version of NodeJS and it would be nice to update to stable (v13 as of creation of this issue). This might require some changes to some dependencies as what is holding us back from updating now are dependencies (`sha3` and `keccak256` for example) failing to build as they require older deprecated NodeJS C++ APIs.

**Comment by bh2smith** [comment]
Is this related to #239?

**Comment by nlordell** [comment]
> Is this related to #239?

No, this is to go from v10 to v13, this is related to the build errors you get when you do an `npm install` on latest stable NodeJS.

**Comment by alfetopito** [comment]
~Be aware that there are (were?) issues with node v13 and sha3/keccak packages. @Velenir might be able to provide more context.~

Never mind, I see that this is in the description already, which I missed the first time I read it (facepalm)

**Comment by nlordell** [comment]
We now work with the current Node LTS since #704 which is what NodeJS recommends using.
