### ISSUE TITLE
NPM scripts for withdraw features

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#33]
for testing purposes it will be important to have the following js-scripts

- `requestWithdraw`
- `applyWithdraws`
-  `claimWithdraw`

**Comment by bh2smith** [comment]
request Withdraw featured in #41

**Comment by bh2smith** [comment]
apply Withdraws featured in #42

**Comment by bh2smith** [comment]
Question regarding specifics of `claimWithdraw` script

The input parameters in the contract function are 
```
(slot, inclusionIndex, accountId, tokenId, amount, proof)
```

It is already clear that the script would query the database and compute the Merkle `proof` on its own, but also (from the user's perspective), the `inclusionIndex` will not be readily available. 

This implies that one would only be expected to supply `slot, accountId, tokenId, amount` while the script takes care of the rest. However, these values don't necessarily uniquely determine the inclusion index (since the same account may have requested two withdrawals of the same amount and token in the same batch). 

At this point, we can safely say that neither the Merkle proof or inclusion index should be specified by the script, and that this ultimately results in non-uniqueness of the DB search query. We may consider some of the following options;

- Have the query return the first `unclaimed` index (and proof) from the given `slot, account, token, amount`

- Have the return all of the `unclaimed` results from a given slot and claim them (this would result in multiple signatures).

At this point we see that non-uniqueness is inevitable and have a few options for how to proceed. Processing several transactions at once is likely undesirable (from a UI perspective). Also, because of this non-uniqueness we could also lift the condition that any of token, slot or amount not be required by the script. Lifting these parameters could each come result in other undersired consequences, 

**Examples**

- Not providing `slot` would result in an unreasonably large search space for the DB query

- Not providing `token` could be confusing to the user

- Not providing `amount` actually might be a good idea. If we go with the script claiming the first unclaimed  withdrawal bases on `slot, accountId, tokenId` this would not result in any more trouble than `slot, accountId, tokenId, amount`.

@fleupold and @joso do you have any thoughts regarding this topic? If not, I would lean towards the final statement that the script takes `slot, accountId, tokenId` queries the DB for the first valid (unclaimed) withdraw matching that description and claim that one.

**Comment by fleupold** [comment]
Thanks @bh2smith for the elaborate explanation and thorough thinking. 
I think any of the outlined behaviours is ok for a start, since this script is primarily used to demo interactions and won't be the final UI for users to claim their withdraws.
I could envision that it would be most convenient for a developer to withdraw all matching claims and allow the command-line arguments to be optional (in that I can withdraw all pending claims of a certain accountId if I only specify that, but can drill down more specifically).

As a start however, I think what you suggested is perfectly fine and we shouldn't spend too much time to make this script prematurely convenient.

**Comment by bh2smith** [comment]
claimWithdraws resolved by #45
