### ISSUE TITLE
Move To Typescript

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-contracts#330]
Type safety is :ok_hand:

**Comment by bh2smith** [comment]
At this point, all the referenced PRs take care of the TS migration of the `test/` directory and the next question is with regards to whether or not we should also migrate `scripts/`. These are essentially just little tidbits of code (many of which that should be scrapped - e.g. wait_seconds) used to interact with the exchange. Some of these scripts are much more elaborate than others (i.e. `deposit`, `withdraw` and `place_order` versus `ensure_owl_liquidity`, `transitive_orderbook`, `place_spread_orders` etc...). 

We should keep in mind that some/many of these simple scripts were created for the purpose of exposing easy access command for our end-to-end testing of `dex-services` once upon a time before ethcontracts (i.e. when we were testing e2e in bash). Perhaps now, such things are no longer necessary.

If we do decide to migrate these scripts we will have to adapt our current framework of exporting async functions with a callback and throwing the entire script into a try catch. That is, or current standard for these scripts is:

```js
module.exports = async (callback) {
  try {
    doTheThing()
    callback()
  } catch(err) {
    callback(err)
  }
}
```
From what I have seen so far, this will not be something that can simply be pasted directly in to a TS file.

**Comment by fleupold** [comment]
My first intuition would be we should convert these scripts as well to make this repo a ts first repo. Maybe you can start converting a simple script and we look at what the benefit vs. the work involved is?

**Comment by bh2smith** [comment]
Yes, this is something I have already attempted... but I will need to look closer at getting over this async-callback hurdle. Will come back to this once I get #798 merged.

**Comment by bh2smith** [comment]
Next Question (once #822 is merged)

Should we also translate the migration scripts (`migrations/*.js`)? I see very little benefit in this apart from having no trace of JS in the codebase.

**Comment by fleupold** [comment]
I think it's better to leave this as is, since the code is minimal and simple and I'd assume it will be hard to tell truffle migrate to look for its files in some other directory.

**Comment by bh2smith** [comment]
Sounds good to me. We should be aware that there is a bit of JS left in `src/migrations` which are imported from the migration scripts... 


I would also like to propose (once #822 is merged) that we put all the scripts which can only be used in ganache into a subdirectory `scripts/dev`. These would be, for example, 

- setup_environment
- setup_thegraph_data
- wait_seconds and 
- close_auction

**Comment by fleupold** [comment]
I like the idea of having a `scripts/ganache` subfolder

**Comment by nlordell** [comment]
So much purple:
![image](https://user-images.githubusercontent.com/4210206/83638374-5574de80-a5a9-11ea-9f0d-723ef0d82ab4.png)

I really like a dev scripts idea as well. :+1: for `scripts/ganache`

**Comment by nlordell** [comment]
> I think it's better to leave this as is, since the code is minimal and simple and I'd assume it will be hard to tell truffle migrate to look for its files in some other directory.

I took a look at the TypeChain started project and they also have issues with migration and Truffle. I also agree its probably better to leave these as is.
