### ISSUE TITLE
Auction solution doesn't require fee token price

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#331]
In order to avoid the so called "Price Scaling Hack", we have recently (#240)  imposed that the `feeToken` price be fixed at `10^18` (or 1 ether). Currently the price vector requires that all touched token prices be passed along with `submitSolution` and, since the fee token is always touched, always verifies that it is equal to this fixed value. To this end, such a value is simply not necessary to be provided to the contract which can simply assume this value. 

Such a change would result in minor (negligible) gas savings and also require changes in the [dex-services](https://github.com/gnosis/dex-services) codebase.

**Comment by fleupold** [comment]
Let's close when dex-services PR is merged.
