### ISSUE TITLE
Competing solutions to be at least 1% better

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#332]
In order to prevent marginal solution improvements by including what @koeppelmann is calling "dust orders" (i.e. those which have already been 99.9% filled, with a tiny/infinitesimal,  remaining sell amount), we would like the smart contract to impose that solutions only be considered "better" if their utility evaluation is at least a fixed percentage better than the previous.

## Example Dust Order

![dust_order](https://user-images.githubusercontent.com/11778116/69716302-0cc7fe80-110a-11ea-9c9e-f6eb42c34aa1.png)

## Implementation Suggestion 

 Because of loss of precision with integer division, I would propose the following (integer) evaluation
```py
new / old > 1.01 <==> new * 100 > old * 101
```
This would mean only a small adjustment to the `checkAndOverrideObjectiveValue` function in smart contract as follows:
```js
// Percentage that competing solution must be better than current to be accepted
uint256 public constant IMPROVEMENT_FACTOR = 1;
function checkAndOverrideObjectiveValue(uint256 newObjectiveValue) private {
    require(
        newObjective.mul(100) > currentObjective.mul(100.add(IMPROVEMENT_FACTOR)) ,
        "Solution must be at" least x% better than current"
    );
    latestSolution.objectiveValue = newObjectiveValue;
}
```

⚠️ - This should not require changes to the `dex-services` driver (as pointed out by @nlordell) since the driver first checks if the solution would be accepted!

**Comment by nlordell** [comment]
@bh2smith I don't think this requires a change to `dex-services` since we ask the contract to check the solution would be accepted before submitting it. So the contract would reject the marginally better solution and the solution would not be submitted by the driver.

We should test to make sure this is true but I imagine it to be the case.

**Comment by nlordell** [comment]
Also, why 1%?

**Comment by nlordell** [comment]
I think we should use the "numerator/denominator" style representation as well like we do with the fees. So here we could do a "improvement_numerator" and the calculation would become
```
// Percentage that competing solution must be better than current to be accepted
uint256 public constant IMPROVEMENT_NUMERATOR = 100;
function checkAndOverrideObjectiveValue(uint256 newObjectiveValue) private {
    require(
        newObjective.mul(IMPROVEMENT_NUMERATOR) > currentObjective.mul(IMPROVEMENT_NUMERATOR + 1) ,
        "Solution must be at least x% better than current"
    );
    latestSolution.objectiveValue = newObjectiveValue;
}
```

This allows to represent different %x values more easily: 0.1% would be `IMPROVEMENT_NUMERATOR = 1000`, 2% would be `IMPROVEMENT_NUMERATOR = 50`, etc.

**edit**: added some stuff

**Comment by bh2smith** [comment]
> Also, why 1%?

This value was proposed by @koeppelmann only as a first thought, but it can be adapted or changed

> `IMPROVEMENT_NUMERATOR`

I completely agree and this is a very good suggestion! However, I would prefer to call this `IMPROVEMENT_DENOMINATOR` since it would be on the bottom.

> I don't think this requires a change to dex-services

This is excellent/fantastic news and means we could implement the changes much easier!
