### ISSUE TITLE
Coherent Balance Information

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#336]
This issue is directly related to the issue in [dex-react](https://github.com/gnosis/dex-react/issues/228) which points out that the information returned in the following functions is incoherent:

- `getPendingDepositAmount`
- `getPendingDepositBatchNumber`
- `getPendingWithdrawAmount`
- `getPendingWithdrawBatchNumber`
- `getBalance`

I revised implementation will make use of the code proposed [here](https://github.com/gnosis/dex-react/issues/228#issuecomment-559445756) and (possibly) if necessary, expose an additional view which returns all the relevant information in a single query as described [here](https://github.com/gnosis/dex-react/issues/228#issuecomment-559382338).

**Comment by bh2smith** [comment]
I am in the process of putting together a complete justification, with proof, of how our view functions for coherent balances should be evaluated and what should be returned.

## Key facts regarding Epoch Token Locker

- Deposit requests made during the same batch are accumulated (since the funds are transferred during the time of request) while 
- Withdraw requests made during the same batch overwrite previous requests.

_Claim:_ It is not possible to have both a pending and matured request of either type (deposit or withdrawal). 

_Proof:_ To see this, wlog, assume there is matured deposit and we would like to construct a pending deposit (so that we have both). During the call to `deposit`, the contract calls `updateDepositsBalance` which credits and deletes any matured deposit balance. If we had begun from a pending state, the only way to get a matured deposit is to wait until the next batch, which puts us in the first scenario (i.e. beginning with a matured type).  Similarly, if we had begun with matured withdraw, the contract call to request withdraw would first claim the matured balance and delete this element before creating the pending one. Thus, the above claim holds.

Note that for either type (deposit or withdraw) there are three possible "states": These are `None`, `Pending` or `Matured`. What distinguishes these types is the batch index associated with their creation time in relation with current batch index (this discrete analogue to the creation timestamp). More precisely, the state is
- **Matured** when `currentBatch > creationBatch`
- **Pending** when `currentBatch <= creationBatch`
- **None** when there is no request in the contract's storage. This null state, from the contract's perspective would have a `creationBatch = 0` and is logically equivalent to a matured state with value 0. That is to say, do not need additional logic to handle the null scenario for either of deposits or withdraws.

With the above results in place, it suffices to enumerate and elaborate on the remaining possible scenarios (of which, there are 4). These are

1. Simultaneously having both a pending deposit and withdraw

Observation, this can only happen if these requests were made in the same batch.

2. Pending deposit and matured (a.k.a. claimable) withdraw

3. Pending withdraw and matured deposit

4. Both deposit and withdraw are matured


## Example
The following example is meant to touch on the scenarios listed above. Before proceeding we will need some 
### Notation

Assuming a fixed user U and token T (which will be completely surpressed from all further notation as we will only be discussing the Balance, B(U, T), of user U's token T). 

Let `n` denote the user's nonce and let us denote a deposit request as `(d, b)_n` which says, this is the deposit of a value `d` requested at batch `b`. Similarily a withdraw will be denoted `(w, b)_n`. 

For a sequence of deposits and withdraws we write `D = {(d_1, b_1), (d_2, b_2), ...}` and similarily for `W`. 

Consider, then, the following scenario (a bunch of deposits and withdraws all requested during batch 1).


`D = {(1, 1)_1, (1, 1)_2}`
`W = {(1, 1)_3, (0, 1)_4}`


which says that (all within the same batch - 1) this user requested two deposits of 1 and first requested to withdraw 1, but then canceled the withdraw request. The purpose of this example is to discuss what is the actual balance of this user through the batch periods 0, 1 and 2.

_Batch 0:_ 
- It is clear that the balance is 0 for this entire batch.

_Batch 1:_ 
- Based on the deposit request sequence the balance jumps from 0 to 1 and then from 1 to 2 during this batch.
- Note that, because the deposit-transfer was made, this pending deposit balance should be reflected in the users balance immediately (even though it has not "matured").
- Also, a request to withdraw 1 was made here, but this should not be reflected in the actual balance since it has not yet matured.
- Furthermore, within the same batch, a request to withdraw 0 was made, which overwrites the previous request to withdraw 1. Good thing we didn't display any false values by pre-maturely including a pending withdraw in the balance!

_Batch 2:_
- Now that both requests have matured, we should expect to see a claimable balance of 0 and an actual balance of 2

A key point here is that the 2 displayed in the "actual balance" during the latter half of batch 1 may, or may not, be computed in the same way as it is in batch 2 depending on whether a new request is made and the pending information is purged from the contract's storage...


What this example aims to demonstrate is that the actual balance should be computed as follows:

```
actualBalance = storedBalance + (pendingDeposit + maturedDeposit) - claimableWithdraw
```

Where 
- `storedBalance` is the updated state of the account from all prior additions and subtractions incurred.
- The second term (in brackets) is the sum of both pending an matured deposits. Recall that we have proven there cannot ever be both at the same time (i.e. at least one of these terms is always 0). Implementation-wise, this sum simply says "add whatever value is stored in pendingDeposit regardless of the creationBatch".
- `claimableWithdraw` is the amount stored in pending withdraw only if the request has matured. Implementation-wise, this is `pendingWithdraw.amount` if `pendingWithdraw.creationBatch < currentBatch`.


Running this formula through the example above subscripting the actual balance with the user's nonce we find:

_Batch 0:_

```
actualBalance_0 = 0 + 0 - 0 = 0
```

_Batch 1:_

```
actualBalance_1 = 0 + (1 + 0) - 0 = 1
actualBalance_2 = 0 + (2 + 0) - 0 = 2
actualBalance_3 = 0 + (2 + 0) - 0 = 2 
                                ^-- Withdraw request of 1 was made, but is pending
actualBalance_4 = 0 + (2 + 0) - 0 = 2
```

_Batch 2:_

```
actualBalance = 0 + (0 + 2) - 0
                       ^-- Deposits went from pending to matured, 
                ^-- but still not in user's "storedBalance"
```
Suppose now that the user sends two more request transactions during Batch 2: 

`D = (1, 2)_5 and W = (1, 2)_6`

**Now we will see some magic!**

_Batch 2:_

```
actualBalance_5 = 2 + (1 + 0) - 0 = 3 (pending deposit is 1)
                  ^-- previous matured deposits are processed 
                      and moved into storedBalance!
actualBalance_6 = 2 + (1 + 0) - 0 = 3 
                                ^-- requested withdraw not yet claimable!
```
_Batch 3:_

```
actualBalance = 2 + (0 + 1) - 1 = 2
                              ^-- withdraw is now claimable and
                         ^-- deposit moved from pending to matured
```
sending any other request would move all this "temp" storage into stored balance and result in 

`actualBalance = 2 + (0 + 0) - 0`


This is just the beginning of an attempt to formally justify what `getBalance` view function should return. Interested in feedback and will build on this asap.

**Comment by alfetopito** [comment]
It makes complete sense from a client/caller point of view and the examples make it very clear, thanks for taking the time to write it down!

Now, for internal use in the contract, pending withdraws should still be deduced from the available balance, correct? 
If I remember correctly there is an attack vector prevented by this.

**Comment by bh2smith** [comment]
> Now, for internal use in the contract, pending withdraws should still be deduced from the available balance, correct?

This is an important point you have brought up! ~~I will need to confirm with @josojo on this point. I was completely puzzled by the fact that the balance has been evaluated in the way it currently is and have not yet been able to figure out why. This "attack vector" could very well be a reason I was not aware of.~~

**Wait!** No, currently the contract is only including matured withdraws in the `getBalance`evaluation. Here

https://github.com/gnosis/dex-contracts/blob/d424f4b2a2fede850aba04177749d64ec7716c02/contracts/EpochTokenLocker.sol#L175-L184

My proposal is simply to change how it treats deposited information as follows:

```js
    function getBalance(address user, address token) public view returns (uint256) {
        // Stored Balance
        uint256 balance = balanceStates[user][token].balance;
        // Plus deposit (pending or matured)
        balance = balance.add(balanceStates[user][token].pendingDeposits.amount);
        // Add only claimable withdraw amount
        if (balanceStates[user][token].pendingWithdraws.stateIndex < getCurrentBatchId()) {
            balance = balance.sub(Math.min(balanceStates[user][token].pendingWithdraws.amount, balance));
        }
        return balance;
    }
```

Which would align exactly with the `actualBalance` formula described above!

**Comment by fleupold** [comment]
> More precisely, the state is
...  - Pending when currentBatch == creationBatch

Note that it's possible to `requestFutureWithdraw` so a request can be withdraw request can be pending if `currentBatch <= creationBatch`

As for your example, I'd argue the return values should be

| Batch | PendingDeposit | getBalance | pendingWithdraw | claimableWithdraw |
| ---|---|---|---|---|
|0|0|0|0|0|
|1|2|0|2|0
|2|0|0|0|2

Where on the frontend, we can always add pendingDeposit and balance together. I think balance should be perceived as the amount of tokens that I will be able to trade "in the next batch" (thus pending withdraws should be deducted in my opinion).

PendingWithdraws are shown with the timer icon and claimable withdraws are clickable.

**Comment by bh2smith** [comment]
Yes @fleupold  - I like this. Not 100% keen on displaying pending withdraws, but it wouldn't affect too much.

 
At no point in my example is there a withdraw request for 2. Is this an alternate example? Also, in Batch 1, are you sure you want the balance to display 0 here? Because I would disagree. ~~Could you please double check your values here or elaborate some more... Why would I want my balance to display something about the future (especially when it can be overwritten)?~~

Ahhh, I see here. You would like to display pending information. I can _kinda_ see the point... ~~This would also imply that no changes need to be made to the current implementation.~~

Actually, then you claim would be the following

```
actualBalance = storedBalance + (pendingD + maturedD) + (pendingW + maturedW)
```

> Note that it's possible to requestFutureWithdraw

Good point here! Thanks for reminding me!

**Comment by bh2smith** [comment]
@fleupold - Can you confirm that you would be in favour of the following change to the current implementation of `getBalance`?

```js
    function getBalance(address user, address token) public view returns (uint256) {
        uint256 balance = balanceStates[user][token].balance;
        balance = balance.add(balanceStates[user][token].pendingDeposits.amount);
        balance = balance.sub(Math.min(balanceStates[user][token].pendingWithdraws.amount, balance));
        return balance;
    }
```

Which, I claim, coincides with your proposal of including `pendingWithdraws` in the current balance

```py
actualBalance = storedBalance 
    + (pendingD + maturedD) 
    + (pendingW + maturedW)
```

I presume you would also only want to include pending withdraws that are not way far in the future... So actually this formula  would also need to keep that in mind...

**Comment by fleupold** [comment]
@bh2smith Sorry, I messed up the example. I think the table should be.

| Batch | PendingDeposit | getBalance | pendingWithdraw | claimableWithdraw |
| ---|---|---|---|---|
|0|0|0|0|0|
|1|2|0|1|0
|1 after cancelled withdraw|2|0|0|0
|2|0|2|0|0

I wouldn't change the getBalance function as all, as it is used by the StablecoinConverter to verify people have enough balance in the batch that is currently up for solution submission.

I'd either return both amount and expiration date on getPendingDeposit/Withdraw (so that the frontend can decide based on atomic information whether or not to add the pendingDeposit to the Balance and wether or not to show the clock item on the withdraw).

Alternatively, I'd change the logic of getPendingDepositAmount to

```sol
function getPendingDeposit(address user, address token) public view returns(uint256) {
  if (currentStateIndex > balanceStates[user][token].pendingDeposits.stateIndex) {
    return 0
  } else {
    return balanceStates[user][token].pendingDeposits.amount;
  }
}
```

and leave `getPendingWithdrawAmount` as is

**Comment by fleupold** [comment]
@anxolin @alfetopito please let me know what you guys prefer. You are the only client of this API so far thus your choice.

`getPendingWithdrawAmount` and `getPendingWithdrawBatchNumber` will be combined to one method returning both values in a tuple.

For getPendingDeposit we have two options:

1. Make getPendingDepositAmount return 0 if the deposit has matured (by doing the same if check we don in get balances)
2. Do the same as for withdraws (return a tuple with amount and state index, which if in the past indicates the withdraw is already included in the balance).

I slightly prefer 2. as it would be the same for deposit and withdraws and allows more flexibility for the people using this API. But I can understand if you prefer not to have the extra client side logic. 

Would be awesome if you could let me know your thoughts by tomorrow morning (otherwise I'd go with 2.)

**Comment by alfetopito** [comment]
To make sure I understand the proposals, consider we want to display total amount available for user on exchange:

1. For 1, safe to always add `balance` + `pending deposit` 
2. For 2, we would only add `pending deposit` to balance if `deposit batch number` < `current batch id`

Assuming I got this right, I agree `2` provides consistency with `pending withdraw` and I prefer this solution, although it's not consistent with `getBalance`.

~The issue came from the unknown behaviour (for us in the frontend) about `getBalance` calculating the balance based on batchId, while the other supporting methods are not. The solution proposed on `2` for both pending withdraw and deposit simply merges two functions (get amount and get batch id) into one, keeping the old behaviour.
While `getBalance` implementation has the reason for not changing, I would argue it would be more consistent to expose another sort of `getBalance` function to: 1) be batchId agnostic 2) not impact current contract logic.
Then it would make more sense for api consumers to have a consistent behaviour across all balance related functions.~

Maybe I'm overthinking this. `2` should be fine.
