### ISSUE TITLE
Measure the performance of view functions like (getEncodedOrderElements)

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#386]
Measure the performance of view functions like (getEncodedOrderElements)

the performance should be tested on a Rinkeby with infra nodes, to get a feeling of quickly the web pages load for our users

**Comment by josojo** [comment]
Hm...

pls try to run the following command:
```
npx truffle exec  scripts/stablex/get_auction_elements.js --network rinkeby
```
with the current BatchExchange deployment from rinkeby.
`0x89593E017D4A88c60347257DAfB95384a422da09`

I get the following error message:
```
Error: Returned values aren't valid, did it run Out of Gas?    at PromiEvent (/Users/alexherrmann/gnosis/dex-contracts/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:6:1)
    at Function.call (/Users/alexherrmann/gnosis/dex-contracts/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:109:1)
    at module.exports (/Users/alexherrmann/gnosis/dex-contracts/scripts/stablex/get_auction_elements.js:8:77)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I only added 100 orders... or something like that. If this is really the limit, we should have known better.

**Comment by anxolin** [comment]
It looks like it might be another issue, we can review tomorrow. Cause usually the limit error is shown differently. And 100 seems too small

**Comment by fleupold** [comment]
I do believe it is this error. I found that view functions usually impose the block gas limit (you can configure geth to not have a limit, but I assume this is not what e.g. infura does).

https://github.com/trufflesuite/ganache-core/issues/148

And I confirmed that at least when sending our invocation as a tx, we are exceeding the block gas limit:

https://rinkeby.etherscan.io/tx/0xc6c5720d011c64c779e28962627352fde2fb396c0123942499522c29e103391e

**Comment by josojo** [comment]
Checkout this here from 13 days ago:

```
Hi @talkingant . Earlier this week we added a gas cap of double the block gas limit to eth_call and eth_estimateGas to prevent Denial of Service attacks. I apologize that you ran into this without it being clear in the docs. The intention with setting the limit to double the block gas limit was that it shouldn’t effect existing users since no call should take more than the block gas limit.
```
You can read the whole thread here:
https://community.infura.io/t/gas-limit-on-eth-call/1115/3
But they will change it here:
```
Hi @talkingant after discussing with our team, we’re planning on upping the gas cap limit to 10x the block gas limit but because of the change required we likely won’t be able to update this until the Istanbul fork next week. We pushed the documentation change for now https://infura.io/docs/ethereum/json-rpc/eth_estimateGas 2 to show the limit at 2x block gas limit and we will update the docs when we are able to up this to 10x next week. Are you able to workaround this issue for now? How disruptive is this to your users?
```
I guess this is not sufficient if 100 orders do not work right now than even a 5-10 time increase would not scale for an MVP? So we should run our own nodes for the solver.

**Comment by fleupold** [comment]
Or consider a pagination approach. Btw, I was able to get the data from infura by using the following command:
```js
await instance.contract.methods.getEncodedAuctionElements().call()
```

**Comment by josojo** [comment]
How would pagination work?

**Option 1: grab order per user only**
Should we make the 
`IterableAppendOnlySet.Data private allUsers;` public via a getter function:

`
getUserWithId(uint id) public returns(address){
return allUsers(id)
}
`
And then we grap all orders by iterating over the users?

**Option2: grab orders by selecting fractions of the whole order set**
amend the already existing function getUserOrders() to iterate only over constant a fraction of all orders
```
 function getUserOrders(address user, uint startingIndex, uint endIndex){
if( user == address(0))
{
            user = allUsers.first();
}
j =startingIndex
if (allUsers.size() > 0) {
            for(uint i= startingIndex; i<=endIndex; i++) {            
                elements = elements.concat(getEncodedUserOrder(user, j));
                 j++
                if(j == orders[user].lenght){
               {
                j=0    
                user = allUsers.next(user);
                }
                if (user == allUsers.last) {
                    break;
                } 
           }
        }
        return elements;
```

**Comment by fleupold** [comment]
I benchmarked the the gas cost for calling the function as part of a transaction

```
await instance.contract.methods.getEncodedAuctionElements().call()
```

And was able to query about 250 elements within the 10M block gas limit. However, we can configure our nodes to provide a larger limit for view functions (using `--rpc.gascap`) to query even more elements.

While this is probably not a final solution (we likely want people to access order data via vanilla infura nodes) it might be enough for the very fist alpha deployment.

**Comment by fleupold** [comment]
Regarding the pagination approach:

I think Option 1 would still suffer from similar problems if one market maker decides to place many orders.
So I guess the `page_info` needs to contain both a user ID and an offset and then return some fixed amount of orders starting from there. Should that fixed amount be up for the caller to decide? This way you could still query all orders in one go if you knew you were talking to a specialized full node.

**Comment by anxolin** [comment]
Yep, if we do have this limitations, I agree we need a pagination approach. And I agree on passing both the `startIndex`, `count`. I think I mentioned that in a coupled PRs, but I was unsure of where was the limit exactly. Thanks for reviewing it!

This PR is for modifying the current implementation of `getEncodedUserOrders` right?
What do you want to do with`getEncodedOrders()`? 

I include @alfetopito in the conversation, cause he was using this functions.

**Comment by alfetopito** [comment]
FYI, we are currently using ['getEncodedUserOrders'](https://github.com/gnosis/dex-react/blob/develop/src/api/exchange/ExchangeApiImpl.ts#L97). 

As for the pagination API for this method (`getEncodedUserOrders`), I'd suggest to use `offset` (index to start from) and `pageSize` (how many to get in this response).
Potentially having `offset` and `pageSize` default to 0, meaning that when no parameters are provided the response includes all orders and it's up to the caller adjust accordingly to gas limit.

**Comment by josojo** [comment]
I am closing this issue, as we have solutions:

1) For the front-end, we have the pagination approach for getting orders per user implemented.
2) The solver can be pointed against our nodes: `https://node.rinkeby.gnosisdev.com/ `, where we can have our own configuration to enable all required views.
