### ISSUE TITLE
gas optimization: valid till 0 could mean valid forever

### ISSUE THREAD

**Issue by koeppelmann** [gnosis/dex-contracts#437]
setting the valid till field to 0 could mean the order is valid forever. This would save a bit of gas and would create a canonical representation for orders that are valid until canceled.

**Comment by fleupold** [comment]
@josojo should we consider this as an improvement when we incorporate the auditor's feedback? I think it would make the "isValidOrder" logic slightly more involved (e.g. checking that validFrom is not 0 as this would mean the order has been deleted).

**Comment by alfetopito** [comment]
Dumb suggestion: assume the convention that validUntil == 1 means valid forever instead of 0 for Martin's suggestion to avoid mistaking it by a deleted order.

**Comment by fleupold** [comment]
The point of Martin's suggestion is to save gas by storing a 0 word (which is free). But thinking about it more, the validUntil is only 4 bytes (uint32) padded together with validFrom, buyToken, and sellToken.

Therefore the word itself is unlikely to be 0 overall and thus will not actually save any gas.

**Comment by fleupold** [comment]
Closing this as it is likely unactionable - the validUntil is too small to account for a 0 word and thus we will likely still incur the storage cost as at least either buy or sell token will be non-zero.
