### ISSUE TITLE
[Audit] SubtractBalance should respect available balance

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#448]
Currently subtractBalance just SafeMath subtracts the requested amount from the net balance. However, part of this balance can already be reserved for "matured" withdraw requests and should thus be untouchable.

https://github.com/gnosis/dex-contracts/blob/a7149e93b6f383b06019415e6e5639885d6faeb8/contracts/EpochTokenLocker.sol#L208-L211

This allows an attacker to submit a "valid" solution, which taps into a user's matured withdraw amount. Benign solvers will ignore this amount and thus might be able to match less trades leading to a worse objective value.

The only defense would be to claim the withdraw immediately when it becomes available. Otherwise it will just be reduced to the remaining available amount.

To fix this issue, we should create a regression test demonstrating the attack and then insert the require statement into the method above.

**Comment by bh2smith** [comment]
Oh my! Could you please elaborate on 
>  the require statement

It this some statement involving a comparison of `balance`, `amount` and `matured withdraw value`?

**Comment by bh2smith** [comment]
From our slack discussion, I believe the require to be something like this:

```
amount <= getBalance(user, token) 
```

**Comment by fleupold** [comment]
@bh2smith yes exactly that.
