### ISSUE TITLE
Untested view - hasValidWithdraw

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#450]
The following public view function is not directly tested in the code base.

https://github.com/gnosis/dex-contracts/blob/31e5b4232a314e218804f7a6ed41aa7161c5325a/contracts/EpochTokenLocker.sol#L179-L183

**Comment by fleupold** [comment]
You mean it's only covered indirectly by other logic tests? We do have 100% coverage, If I'm not mistaken.

**Comment by bh2smith** [comment]
> it's only covered indirectly by other logic tests

Yes, exactly. However, after another pass, I have seen that it appears we are not testing view functions anyways so I will close this.
