### ISSUE TITLE
unittest for max gas costs for solver submission

### ISSUE THREAD

**Issue by koeppelmann** [gnosis/dex-contracts#455]
here is a solver tx that submits the max of 25 orders:
https://etherscan.io/tx/0x0ee4fbfc2874415e14d3c7923ff69cb3ffcf3617c10f74746fe6133ec1b1520a
It already consumes >3m gas. The most expensive tx would likely be one that first needs to revert a previous sobmission of 25 orders. I would like to have such a test to know that the number is well bellow any to be expected block gas limit.

**Comment by fleupold** [comment]
@koeppelmann it's 6.2M gas for updating a 25 order solution with a better one. Is that ok?

**Comment by bh2smith** [comment]
Closed by #463
