### ISSUE TITLE
Allow "efficient" paginated query of order book

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#461]
On the current Rinkeby deployment we are no longer able to query all orders with a standard full node (we run out of gas on invoking the view function).

In order to cope with that we have the following options:
1. With the next version of SC we can query for all users (paginated) and then for each user query all their order (paginated).
2. We can use TheGraph to query all orders
3. We can keep the order book in memory and listen for incremental changes via PlaceOrder and OrderCancellation events

The problem with 1) is that it might take a lot of request (O(number_users)) which could potentially take a long time before we can start running the solver. 2) adds a dependency to another service which might be down out of sync or whatever and avoiding that was one of the core ideas behind putting all orders on chain. 3) is significantly more logic in the services (but eventually we likely have to do something in order to start solving as soon as the 5 minute window starts).

Alternatively we could also add yet another view function to the smart contract that allows querying all orders paginated with fewer queries. It would basically take a user address **and** an offset as arguments (+ the desired page size) and then start at the given user's order offset traversing the list of users and orders until the desired page size is reached.
The benefit over solution 1) would be that if we have a 100 users with one order each we still only need a single invocation of the method whereas in 1) we would need 101 queries.

What do you guys think?

@nlordell @josojo @bh2smith

**Comment by nlordell** [comment]
If we also filter out invalid orders, that will make the list even shorter.

**Comment by nlordell** [comment]
I like the new view function suggestion. Like you mentioned the other day, the design of StableX version was to have everything easily stored and retrievable on chain so this falls in line with that.

**Comment by fleupold** [comment]
> If we also filter out invalid orders, that will make the list even shorter.

This could be backed by more profound research, but my hunch is that it's really the SLOAD which is responsible for most of the gas cost (800 per word). Sending the data back should only be the cost of memory (low) or transaction data (4 gas per zero word), but I'm not exactly sure how return values are priced.

**Comment by bh2smith** [comment]
All options seem somewhat reasonable with (3) being, as @nlordell mentioned, the most inline with the vision for Version 1. However, I would say that option (2) is more in line with Version 2 vision and somewhat depends on our roadmap/timeline for abandoning for the V2 release. Also, we already have the infrastructure for graph queries in place with the Snapp code. So I would think that option 2 or 3 are "best" depending on our roadmap.

**Comment by fleupold** [comment]
@bh2smith have you considered becoming a politician? 

> So I would think that option 2 or 3 are "best" depending on our roadmap.

What about the alternative with having another view function on the contract?

**Comment by bh2smith** [comment]
I ignored option 1 because I consider it the least viable option. You mentioned yourself an example with too many queries... I also think this will become a problem once users have hundreds of cancelled orders...

Perhaps a combination of option 1 along with filtration of expired, or deleted orders could work.

**Comment by josojo** [comment]
I thought that we would go with the solution proposed here:
https://github.com/gnosis/dex-contracts/issues/386#issuecomment-569215995

We would host our own node, which does not have the gas limitations on view functions

**Comment by nlordell** [comment]
Have we tried with the Gnosis rinkeby node instead of Infura?

**Comment by fleupold** [comment]
With 300M gas limit, we can query the list again. cc @denisgranha as this for now is only a temporary solution and we need benchmarking to see what max gas limit would be ok to support long term.

> We would host our own node, which does not have the gas limitations on view functions

We can do that, but for safety we might still want to have a smart contract level fallback?
