### ISSUE TITLE
Should not be able to place order for non-existant tokens

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#462]
Rinkeby is currently failing with the following error

> Must have ID to get Address

Chasing the issue it seems to come from [here](https://github.com/gnosis/dex-contracts/blob/a7149e93b6f383b06019415e6e5639885d6faeb8/node_modules/@gnosis.pm/solidity-data-structures/contracts/libraries/IdToAddressBiMap.sol#L19). Chasing it further, it turns out that `getEncodedUserOrders` will fail if we place an order for a token that is not yet listed:

https://github.com/gnosis/dex-contracts/blob/a7149e93b6f383b06019415e6e5639885d6faeb8/contracts/BatchExchange.sol#L382-L393

In particular `tokenIdToAddressMap` is failing to look up an address for unlisted tokens.

Therefore, we should add a check that both sell and buyToken are listed when placing an order here:

https://github.com/gnosis/dex-contracts/blob/a7149e93b6f383b06019415e6e5639885d6faeb8/contracts/BatchExchange.sol#L464-L474

As a regression test we should make sure we can `getEncodedUserOrders` even in the presence of unlisted token orders.

**Note that if this had been detected post launch, it could have still been tackled by using a wrapper contract for doing the querying.**

**Comment by bh2smith** [comment]
> As a regression test we should make sure we can `getEncodedUserOrders` even in the presence of unlisted token orders.

I don't see the benefit of such a regression test unless we plan to change something about the view function.

**Comment by josojo** [comment]
Another way to solve this would be to implement a try and catch for this function:
`tokenIdToAddressMap`.
This would have the advantage that we would save 1600 gas per order placement.

**Comment by bh2smith** [comment]
> Another way to solve this would be to implement a try and catch for this function

I am unaware of any try-catch functionality in solidity... Are you suggesting we allow orders for unlisted tokens and somehow handle the problem in the view function?

**Comment by josojo** [comment]
Yes exactly.
I am also not so familiar with try and catch, but it should work, as explained here:
https://blog.polymath.network/try-catch-in-solidity-handling-the-revert-exception-f53718f76047

**Comment by bh2smith** [comment]
I am not sure this would be the best idea for the following reason:

- We allow users to place orders for non-existent tokens
- We implement the following try catch inside `getEncodedUserOrders` (as suggested)

```js
if (IdToAddressBiMap.hasId(registeredTokens, buyToken)) {
    elements = elements.concat(
        encodeAuctionElement(user, getBalance(user, tokenIdToAddressMap(orders[user][i].sellToken)), orders[user][i])
    );
}
else {
    emit FailedToGetOrderBecauseMissingToken(OrderInfo);
}
```

Furthermore, there is probably more gas consumed when checking for IDs on every order.

Could you please elaborate on these expectations?

**Comment by fleupold** [comment]
I'd also argue that 1600 gas for order placement (I assume this is derived from two SLOADs inside it IdToAddressMap implementation) is not significant. Moreover gas optimization was overall out of scope for the MVP (we have made a few careful exceptions, but I don't think this one is worth it). We'd be saving about half a cent.

Semantically it is also very weird to have orders in the system for which a token is not yet defined. Thus I think it's easier to reason about the system if such a weird state cannot be reached in the first place.

**Comment by josojo** [comment]
Yeah, I don't know.
For sure the gas costs are not significant. So I am fine with taking it out.
 It is just in the perspective to the newest gas optimization proposed by Martin: https://github.com/gnosis/dex-contracts/issues/419 -which we did accept - I think that overall, we could safe more gas here. This would be the case as order placement happens much more often compared to trading these unlimited orders.

But yeah, gas efficiency was out of scope.

**Comment by bh2smith** [comment]
Ok, then! It appears we have reached a consensus! We can always open this up again in the future f necessary.
