### ISSUE TITLE
[Tests] Reduce test times by await Promise.all

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#483]
A good candidate for this is the recent Large Ring Trade example introduced in #476

**Comment by fleupold** [comment]
I looked into this but wasn't able to get significant reductions. It looks like ganache is single threaded and the test time is mainly bound by the EVM implementation in js.

Therefore parallelising txs doesn't really help. 

Basically, I was only able to reduce the large ring trade example by ~3s.
