### ISSUE TITLE
Update OpenZeppelin Dependency

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#523]
At this moment our open-zeppelin dependency is on a specific commit hash that included `SafeCast` functionality. It appears this has been included in their latest release v2.5.0

See [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#250-2020-02-04)

We should update this, if there aren't too many breaking changes.

**Comment by fleupold** [comment]
I don't understand this task. Wouldn't merging #521 achieve exactly this?

**Comment by bh2smith** [comment]
Yes. I hadn't seen that.
