### ISSUE TITLE
Consider disabling dependabot 

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-contracts#534]
Now that the contracts have been audited, should we:
1) disable dependabot to not accidentally change the output bytecode from the contract so that it is different than the audited version (for example compiler changes when updating Truffle)
2) check that the bytecode does not accidentally change with CI

**Comment by fleupold** [comment]
We decided against it as the bytecode was not audited or formally verified. Also as we are likely going to keep developing the contracts they should stay up to date.
