### ISSUE TITLE
Order Collection

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#54]
One should be able to submit a *limit order* of the following form

- **Buy** at most `X` of token `i` for token `j` if price `p_{i, j} < P`
- **Sell** at most `Y` of token `i` for token `j` if price `p_{i, j} >= P`

@twalth3r could you please confirm the order types that should be collected by the contract?

Expressing a `Sell` Order in terms of integers should be as follows:

- `buyToken: uint8`
- `sellToken: uint8`
- `buyAmount: uint`
- `sellAmount: uint`
- `priceBuyToken: uint`
- `priceSellToken: uint`

**Comment by twalth3r** [comment]
@fleupold - Are we still focusing on limit sell orders only?

**Comment by twalth3r** [comment]
@bh2smith - It would need to be `p_{i,j} >= P`, i.e., the price of the token that you want to sell w.r.t. to the buy-token needs to be equal or above some limit.

**Comment by fleupold** [comment]
Discussed in #56 

I think for now we are still focussing on one type of order

**Comment by bh2smith** [comment]
1 day spent
