### ISSUE TITLE
Deposit Slot Limit

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#6]
Since one needs to provide snark proofs for all state transitions, there is a technical limit on the number of deposits that can be included/applied from a single deposit slot.

Thus, a counter must be included for each active deposit hash so that technical limitations of the SNARK technology are not exceeded.

**Comment by bh2smith** [comment]
Although limits have been included, we can't test with ganache because we are unable to fit more than 1 transaction per block here. Thus the deposit limit is never reached before the block limit on a deposit slot

**Comment by fleupold** [comment]
You can achieve more than 1 transaction per block in ganache, if you disable "automining"

**Comment by bh2smith** [comment]
Please tell me more! Maybe you can show me sometime.

**Comment by fleupold** [comment]
https://ethereum.stackexchange.com/questions/44809/how-to-properly-simulate-mining-time-with-ganache-cli

**Comment by bh2smith** [comment]
Very cool. We should start testing with this at some point to see if we can actually reach MAX_DEPOSITS before the block time is up.
