### ISSUE TITLE
Conditional Coverage

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#61]
Currently (although we do have 100% Line and Branch Coverage), we do not have exhaustive conditional coverage:

### Example:

Check that all batches can be filled to their maximum capacity and then move to the next once full. This applies to deposit, withdraw and order batches.

### Solution:

This will require fitting many transactions into a single block when testing with ganache (since there are 1000 orders allowed in a batch, but the batch times out after 20 blocks).

**Comment by fleupold** [comment]
@bh2smith how are you going to fit many transactions into one block? 
I think it would be nice to add that detail to the solution so that everyone knows how to tackle this task.

**Comment by bh2smith** [comment]
> how are you going to fit many transactions into one block?

Unfortunately, @fleupold, a full solution is not yet apparent. Best I can do is provide some more elaborate suggestions.

Notice that the command `ganache-cli -b 1` tells ganache to mine blocks only every second (rather than automatically). This would allow us to collect enough requests to fill a batch before the slot becomes inactive (i.e. after 20 blocks). Unfortunately, this approach will not work with all of the other existing tests because we will have to fill the code with a bunch of sleep statements.

### Best foreseeable approach

Cover these scenarios as part of the integration testing (so not to affect the runtime of unit tests). During integration tests one can simulate a more realistic mining environment (i.e. one second block times as opposed to immediate).

**Comment by fleupold** [comment]
You could also create a wrapper smart contract that invokes e.g. `place_order` 1000 times in one transaction.

**Comment by bh2smith** [comment]
> You could also create a wrapper smart contract that invokes e.g. place_order 1000 times in one transaction.

I like it very much. Let's aim to do it this way.

**Comment by bh2smith** [comment]
The first of three batches to test for fullness (in order to achieve full conditional coverage) was merged in #120 (for full order batches).

It remains to conditionally test

1. **Full Deposit Batches**
2. **Full Withdraw Request Batches.**

For these, we may have to write a smart contract to place multiple deposits and withdraws in a single transaction (in order to fill the batches before block time is reached).
