### ISSUE TITLE
[DevPortal] Write a tutorial on how to integrate dex-contracts

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#714]
Since we want people to build integrations with our protocol, they need to know how they can integrate our smart contracts in their repository.

The most recent relatively small use case in which we did this ourselves is the the SNX liquidity integration. Maybe we can write a small tutorial how starting from a new truffle project we can create a script that copies liquidity from some other exchange (e.g. uniswap or kyber) to Gnosis Protocol.

**Comment by bh2smith** [comment]
https://github.com/bh2smith/dex-integration-tutorial

Still a few open issues but essentially finished!

**Comment by bh2smith** [comment]
Repo moved to gnosis github:

https://github.com/gnosis/dex-integration-tutorial
