### ISSUE TITLE
[Easy] Linking Library to contract deploys contract

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#80]
In the following migration script, there is no need to keep line 9 (since the linking somehow deploys the contract to the same address as the Library).

https://github.com/gnosis/dex-contracts/blob/40fdaaf32ecb6370f070691340270a040d2523a6/migrations/3_batch_auction.js#L6-L12

This could equivalently be migrated as 

```js
module.exports = function (deployer) {
  deployer.deploy(BiMap).then(() => {
    deployer.link(BiMap, SnappAuction)
  })
}
```

**Comment by fleupold** [comment]
I wonder if creating a PR that fixes this, would take roughly the same time as creating this issue 😉

**Comment by bh2smith** [comment]
Actually, it turns out, we need to do something like the following (in order for SnappAuction to be deployed)


```js
module.exports = function (deployer) {
  deployer.deploy(BiMap)
  deployer.link(BiMap, SnappAuction)
  deployer.deploy(SnappAuction) 
}
```
