### ISSUE TITLE
Await Token Info in Parallel

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#868]
This method is currently inefficient and slow when used to fetch many tokens at once. This could be easily improved by sending out EVM queries in parallel (i.e. with `await Promise.all`).

https://github.com/gnosis/dex-contracts/blob/f5a3dbc696c12bb6af2ea5eee97c703084c84d1a/src/fee_token_liquidity.ts#L29-L51

While improving this, it would also be nice to refactor this to use the batch exchange viewer contract changes that were introduced in #860

**Comment by nlordell** [comment]
I would suggest using https://web3js.readthedocs.io/en/v1.2.9/include_package-core.html?highlight=batch#batchrequest

This would send all the EVM calls to the node in a single batch request, which would (in theory) allow the node to better optimize the access to blockchain data and improve performance even further.

**Comment by bh2smith** [comment]
Very nice suggestion! Thanks @nlordell. This also means we now have many other places we can improve with this!

**Comment by bh2smith** [comment]
@nlordell - Not sure that we have access to the web3 artifact from within this method. Is this going to be more involved that originally expected? Do I really want to pass this into the function...?

**Comment by nlordell** [comment]
> Not sure that we have access to the web3 artifact from within this method

I *think* you have access to the underlying Web3 contract instance with `instance.contract`.
