### ISSUE TITLE
Multi-order Submission for Regular Accounts

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#95]
"Order placement function accepts arrays of order parameters and throws several events."

Currently users must submit their orders individually paying gas fees for each order transaction. It would be nice to be able to submit multiple orders in a single transaction (this would reduce the gas costs for multiple orders and also enable us to unit test what happens when an order batch is filled before the batch closes. In this case, several events or type `SellOrder` would be emitted.

**Comment by bh2smith** [comment]
@josojo and/or @fleupold 

How do we expect to pass multiple orders in to the `multiOrder` function? At the moment I am thinking 
```
    function placeMultiOrder(
        uint8[] buyTokens,
        uint8[] sellTokens,
        uint128[] buyAmounts,
        uint128[] sellAmounts
    ) public onlyRegistered() {
```
but will have to require that `buyTokens.length() == sellTokens.length() == buyAmounts.length() == sellAmounts.length()` and find this is kinda unattractive. Any suggestions?

**Comment by fleupold** [comment]
Is it possible to pass in an array of structs? Something like:
```
struct Order {
  uint8 buyToken,
  uint8 sellToken,
  uint128 buyAmount,
  uint128 sellAmount
}

function placeMultiOrder(Order[] orders) ...
```

Otherwise we could also pass it in already encoded as a byte array. I agree that having these 5 with implicitly matching indices is kind of weird.

**Comment by fleupold** [comment]
Another thought is if we should here also allow people to place order on the behalf of others. As in they can provide an external signature instead of deriving the trader accountId from msg.sender.

Or is this a separate task?

**Comment by bh2smith** [comment]
I would think this is a separate task!

**Comment by josojo** [comment]
Yeah, definitively a separate task.

**Comment by josojo** [comment]
>but will have to require that buyTokens.length() == sellTokens.length() == buyAmounts.length() == sellAmounts.length() and find this is kinda unattractive. Any suggestions?

I think this is not needed. We can just read the length of one of these arrays and if the evm wants to access an "empty element" it will just throw

**Comment by fleupold** [comment]
I think it's a really unintuitive way to specify the data. I'd much prefer if each order could be a continuous blob of data or a struct.

**Comment by bh2smith** [comment]
> I think it's a really unintuitive way to specify the data. I'd much prefer if each order could be a continuous blob of data or a struct.

This is why I asked... It just sucks encoding the orders on the outside.

**Comment by bh2smith** [comment]
If we are going to pass encoded (aka packed) orders into the multi-order, we might as well also be refactoring how orders are submitted in all scenarios. 

Also @josojo 

>  think this is not needed. We can just read the length of one of these arrays and if the evm wants to access an "empty element" it will just throw

If this is ok will all of us, then I can live with this. Unfortunately, if we default to the expectation of throwing, it would appear as if it were an unconsidered case in the contract's logic. Not sure if this is a concern? How do we unit test such "throws"?

**Comment by josojo** [comment]
> I think it's a really unintuitive way to specify the data. I'd much prefer if each order could be a continuous blob of data or a struct.

I am unsure, but for sure okay with both solutions

>Unfortunately, if we default to the expectation of throwing, it would appear as if it were an unconsidered case in the contract's logic. Not sure if this is a concern? How do we unit test such "throws"?

Yeah, good point.

**Comment by fleupold** [comment]
> we might as well also be refactoring how orders are submitted in all scenarios.

I think submitting a single order can stay the way it is (although if people feel strongly I wouldn't object a change), but I'd argue it should be the same for submitting standing orders.

**Comment by bh2smith** [comment]
> I think submitting a single order can stay the way it is (although if people feel strongly I wouldn't object a change), but I'd argue it should be the same for submitting standing orders.

I have just created an issue that I think would be good for onboarding a new contributor regarding this task. See #101. What do you think?

**Comment by fleupold** [comment]
My comment was regarding the arguments that the `placeOrder` function takes. Should this be a packed blob or 4 separate arguments (buyToken, sellToken, buyAmount, sellAmount).

**Comment by bh2smith** [comment]
> My comment was regarding the arguments that the placeOrder function takes. Should this be a packed blob or 4 separate arguments (buyToken, sellToken, buyAmount, sellAmount).

Yes I understand that part, I was referring to the event emission. However, then the contract will have to unpack it in order to have meaningful events for orders. My comment above was specifically about how events are emitted. 

These are two somewhat disjoint topics:
1. events emitted on order placement and 
2. how orders are encoded on request).
